name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release
      
      - name: Run tests
        run: dotnet test --configuration Release
      
      - name: Publish artifact
        run: dotnet publish --configuration Release --output ./publish
        
      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          title: Released
      
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: test
          files: ./publish/BankAccount.dll
